name: Run GolangCI-Lint and Makefile Test

on:
  pull_request:
    branches:
      - main
      - develop
  push:
    branches:
      - main
      - develop

jobs:
  lint:
    name: Lint Code with GolangCI-Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go 1.24
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'  # Ensure we use Go 1.24

      - name: Verify Go Version
        run: go version

      - name: Install Protobuf Compiler and Plugins
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler
          go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

      - name: Install Dependencies
        run: |
          go get k8s.io/klog/v2
          go mod tidy
          go mod download
          go mod vendor  # Ensure all dependencies are available

      - name: Install GolangCI-Lint with Go 1.24
        run: |
          GOBIN=$(go env GOPATH)/bin go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

      - name: Verify GolangCI-Lint Version
        run: golangci-lint --version

      - name: Run GolangCI-Lint
        run: golangci-lint run --timeout=5m

      - name: Run Makefile Test
        run: make test
